### ISSUE TITLE
error running "docker build"

### ISSUE THREAD

**Issue by ulrichard** [commerceblock/lockbox#39]
The first thing I did after checking out this repo is running "docker build -t commerceblock/lockbox ." as instructed in the readme.
This led to the following error:

error: failed to select a version for the requirement `hmac = "^0.5.0"`
candidate versions found which didn't match: 0.11.0, 0.10.1, 0.10.0, ...
location searched: crates.io index
required by package `rusoto_core v0.36.0`
    ... which is depended on by `rusoto_dynamodb v0.36.0`
    ... which is depended on by `serde_dynamodb v0.2.0 (https://github.com/KZen-networks/serde_dynamodb#cbb9562c)`
    ... which is depended on by `server v0.1.4 (/root/lockbox/app/server)`

It looks like https://github.com/ZenGo-X/serde_dynamodb was last updated three years ago.

**Comment by lawlawlaw** [comment]
> The first thing I did after checking out this repo is running "docker build -t commerceblock/lockbox ." as instructed in the readme. This led to the following error:
> 
> error: failed to select a version for the requirement `hmac = "^0.5.0"` candidate versions found which didn't match: 0.11.0, 0.10.1, 0.10.0, ... location searched: crates.io index required by package `rusoto_core v0.36.0` ... which is depended on by `rusoto_dynamodb v0.36.0` ... which is depended on by `serde_dynamodb v0.2.0 (https://github.com/KZen-networks/serde_dynamodb#cbb9562c)` ... which is depended on by `server v0.1.4 (/root/lockbox/app/server)`
> 
> It looks like https://github.com/ZenGo-X/serde_dynamodb was last updated three years ago.

Hello, thank you for highlighting this issue. We are applying fixes and will add an update shortly.

**Comment by tomt1664** [comment]
This was caused by some yanked dependencies and has been resolved.
